<table class="bluedream">
	<thead>
		<tr>
			<th>ID. 
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=id&type=asc"><img src="<?php echo $this->baseUrl('images/arrow_up.gif') ?>" /></a>
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=id&type=desc"><img src="<?php echo $this->baseUrl('images/arrow_down.gif') ?>" /></a>
			</th>
			<th>Treść pytania
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=text&type=asc"><img src="<?php echo $this->baseUrl('images/arrow_up.gif') ?>" /></a>
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=text&type=desc"><img src="<?php echo $this->baseUrl('images/arrow_down.gif') ?>" /></a>
			</th>
			<th>Punkty
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=weight&type=asc"><img src="<?php echo $this->baseUrl('images/arrow_up.gif') ?>" /></a>
				<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'question'), NULL, 'default') ?>?order=weight&type=desc"><img src="<?php echo $this->baseUrl('images/arrow_down.gif') ?>" /></a>
			</th>
			<th>Załącznik</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php $i = 0 ?>
	<?php foreach($this->questions as $question): ?>
		<tr>
			<td><?php echo $question['id'] ?></td>
			<td><?php echo $this->escape($question['text']) ?></td>
			<td><?php echo $question['weight']?></td>
			<td>
				<?php if ($question['file']): ?>
				<a href="<?php echo $this->url(array('action' => 'attachement', 'controller' => 'question', 'id' => $question['id']), NULL, 'default') ?>">Pobierz</a>
				<?php endif?>
			</td>
			<td>
				<a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'question', 'id' => $question['id']), NULL, 'default') ?>">Edytuj</a> |
				<a href="<?php echo $this->url(array('action' => 'remove', 'controller' => 'question', 'id' => $question['id']), NULL, 'default') ?>" class="confirm">Usuń</a>
			</td>
		</tr>
	<?php endforeach ?>
	</tbody>
</table>