<link class="include" rel="stylesheet" type="text/css" href="/css/jquery/jqplot/jquery.jqplot.min.css" />
<script language="javascript" src="/js/jquery/jqplot/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="/js/jquery/jqplot/plugins/jqplot.pieRenderer.min.js"></script>
<script type="text/javascript" src="/js/jquery/jqplot/plugins/jqplot.donutRenderer.min.js"></script>

<?php $i = 0; foreach ($this->groups as $group): ?>
<h1>Grupa '<?php echo $group['name']?>'</h1>

<div id="stats_<?php echo $i ?>">

</div>

<script language="javascript">
$(document).ready(function(){
	  var data = [
	    ['Zaliczyli', <?php echo $group['stats']['passed'] ?>], ['Niezaliczyli', <?php echo $group['stats']['not_passed'] ?>]
	  ];
	  var plot1 = jQuery.jqplot ('stats_<?php echo $i ?>', [data], 
	    {
	      seriesDefaults: {
	        // Make this a pie chart.
	        renderer: jQuery.jqplot.PieRenderer, 
	        rendererOptions: {
	          // Put data labels on the pie slices.
	          // By default, labels show the percentage of the slice.
	          showDataLabels: true
	        }
	      }, 
	      legend: { show:true, location: 'e' },
	      width: 10,
	      height: 200
	    }
	  );
	});
</script>

<h2>Statystyki odpowiedzi użytkowników</h2>

<table class="bluedream">
	<thead>
		<tr>
			<th>Imię i nazwisko</th>
			<th>Wynik (%)</th>
			<th>Ocena</th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($group['stats']['users'] as $user): ?>
	<tr>
		<td><?php echo $user['name']?></td>
		<td><span style="color: <?php if ($user['result'] >= $this->test['points']): ?>green<?php else: ?>red<?php endif ?>"><?php echo $user['result']?>%</span> (wymagane <?php echo $this->test['points']?>% żeby zaliczyć)</td>
		<td>
		<?php
			if (!empty($this->test['3_5'])) {
				if ($this->test['5'] <= $user['result']) {
					echo "5";
				} elseif  ($this->test['4_5'] <= $user['result']) {
					echo "4.5";
				} elseif  ($this->test['4'] <= $user['result']) {
					echo "4";
				} elseif  ($this->test['3_5'] <= $user['result']) {
					echo "3.5";
				} elseif  ($this->test['points'] <= $user['result']) {
					echo "3";
				} else {
					echo "2.0";
				}
			} else {
				if ($user['result'] >= $this->test['points']) {
					echo "Zaliczone";
				} else {
					echo "Niezaliczone";
				}
			}
		?>
		</td>
	</tr>

<?php endforeach ?>
	</tbody>
</table>


<?php ++$i; endforeach ?>