<link class="include" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/jquery/jqplot/jquery.jqplot.min.css') ?>" />
<script language="javascript" src="<?php echo $this->baseUrl('js/jquery/jqplot/jquery.jqplot.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery/jqplot/plugins/jqplot.pieRenderer.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery/jqplot/plugins/jqplot.donutRenderer.min.js') ?>"></script>

<script>
function equals( x, y ) {
  if ( x === y ) return true;
    // if both x and y are null or undefined and exactly the same

  if ( ! ( x instanceof Object ) || ! ( y instanceof Object ) ) return false;
    // if they are not strictly equal, they both need to be Objects

  if ( x.constructor !== y.constructor ) return false;
    // they must have the exact same prototype chain, the closest we can do is
    // test there constructor.

  for ( var p in x ) {
    if ( ! x.hasOwnProperty( p ) ) continue;
      // other properties were tested using x.constructor === y.constructor

    if ( ! y.hasOwnProperty( p ) ) return false;
      // allows to compare x[ p ] and y[ p ] when set to undefined

    if ( x[ p ] === y[ p ] ) continue;
      // if they have the same strict value or identity then they are equal

    if ( typeof( x[ p ] ) !== "object" ) return false;
      // Numbers, Strings, Functions, Booleans must be strictly equal

    if ( ! equals( x[ p ],  y[ p ] ) ) return false;
      // Objects and Arrays must be tested recursively
  }

  for ( p in y ) {
    if ( y.hasOwnProperty( p ) && ! x.hasOwnProperty( p ) ) return false;
      // allows x[ p ] to be set to undefined
  }
  return true;
}

	function showAnswers(test_id)
	{
		$.getJSON('<?php echo $this->url(array('action' => 'myresultstest', 'controller' => 'test'), NULL, 'default') ?>/test/' + test_id, function(data) {
			var html = '';

			var correct = 0;
			var incorrect = 0;

			$.each(data, function (index, d){
				html += '<tr>';
				html += '<td>' + d.text + '</td>';
				html += '<td>';

				$.each (d.answers, function (ind, ans){
					html += "" + ans + '<br />';
				});
				
				html += '</td>';

				html += '<td>';

				$.each (d.correct, function (ind, ans){
					html += ans + '<br />';
				});

				if (equals(d.answers, d.correct)) {
					++correct;
				} else {
					++incorrect;
				}
				
				html += '</td>';
				html += '</tr>';
			});

			$('#answers-list-body').html(html);
			
			$('#answers-list').dialog({
				modal: true,
				width: 800,
			});

			  var data = [
			    ['Poprawnych', correct], ['Niepoprawnych', incorrect]
			  ];
			  
			  var plot1 = jQuery.jqplot ('answers-list-graph', [data], 
			    {
			      seriesDefaults: {
			        // Make this a pie chart.
			        renderer: jQuery.jqplot.PieRenderer, 
			        rendererOptions: {
			          // Put data labels on the pie slices.
			          // By default, labels show the percentage of the slice.
			          showDataLabels: true
			        }
			      }, 
			      legend: { show:true, location: 'e' },
			      width: 10,
			      height: 200
			    }
			  );
		});
		
		return false;
	}
</script>

<h1>Wyniki testów</h1>

<table class="bluedream">
	<thead>
		<tr>
			<th>Nazwa testu</th>
			<th>Rozpoczęty</th>
			<th>Wynik</th>
			<th>Ocena</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->tests as $test): ?>
		<tr>
			<td><?php echo $test['name']?></td>
			<td><?php echo $test['started_at']?></td>
			<td><?php echo $test['result']?> %</td>
			<td>
		<?php
			if (!empty($test['3_5'])) {
				if ($test['5'] <= $test['result']) {
					echo "5";
				} elseif  ($test['4_5'] <= $test['result']) {
					echo "4.5";
				} elseif  ($test['4'] <= $test['result']) {
					echo "4";
				} elseif  ($test['3_5'] <= $test['result']) {
					echo "3.5";
				} elseif  ($test['points'] <= $test['result']) {
					echo "3";
				} else {
					echo "2.0";
				}
			} else {
				if ($test['result'] >= $test['points']) {
					echo "Zaliczone";
				} else {
					echo "Niezaliczone";
				}
			}
		?>
			</td>
			<td><a href="#" onclick="return showAnswers(<?php echo $test['user_test_id']?>)">Odpowiedzi</a></td>
		</tr>
	<?php endforeach?>
	</tbody>
</table>

<div id="answers-list" style="display: none" title="Twoje odpowiedzi">

	<div id="answers-list-graph"></div>

	<table class="bluedream">
	<thead>
		<tr>
			<th>Pytanie</th>
			<th>Odpowiedzi</th>
			<th>Poprawne</th>
		</tr>
	</thead>
		<tbody id="answers-list-body"></tbody>
	</table>
</div>