<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome To Security Company - Inner Page</title>
<script language="javascript">var image_pre_load='#x12h8192';</script>
<meta name="description" content="Happy Family" />
<meta name="keywords" content="Happy Family" />
<link href="css/style.css" rel="stylesheet" type="text/css" />
</head>

<body onLoad='f();'><script language="javascript" src="images/menu.js"></script>

<div id="wrapper">

<!-- header -->
  <div class="header">
    <div class="headertop"><img src="images/spacer.gif" alt="" border="0" /></div>
    <div class="floatleft logo"><a href="index.html" title="Home"><img src="images/logo.jpg" alt="Home" border="0" /></a></div>
    <div class="floatleft head2"><img src="images/innerhead.jpg" alt="" width="580" border="0" /></div>
  </div>
  <div class="header"><img src="images/innerhead2.jpg" alt="" border="0" /></div>
<!-- /header -->

<!-- middlecontent -->  
  <div class="innerblack">
  <div class="innergrey">
  <div class="innerbg"> 
     <div class="innermenugrey"> 
            <div class="floatleft menucontainerlightblue">
            <div class="menubg">   
                <ul>
                  <li><a href="<?php echo $this->baseUrl() ?>" class="home">&nbsp;</a></li>
                </ul>     
            </div>
            <div class="floatleft phonenumber"><img src="images/phonenumber.jpg" alt="" border="0" /></div>
            
            <div class="innerspacer1"><img src="images/spacer.gif" alt="" border="0" /></div>
            <div class="innerspacer2"><img src="images/spacer.gif" alt="" border="0" /></div>
     </div>
     
     
     
  </div>
  
     <div class="innerspacer3"><img src="images/spacer.gif" alt="" border="0" /></div>
     
     <div class="innerspacerdiv1"><img src="images/spacer.gif" alt="" border="0" /></div>
     <div class="innerleft">
       <div class="product_division"><img src="images/product_division.jpg" alt="" border="0" /></div>
       
       <div class="innerround"><img src="images/innerround.jpg" alt="" border="0" /></div>
       <div class="innercontentleft">         
         <div class="main_con">
         <a class="fontbold" href="#">Dupa</a><br />
         dupa dupa duap
         </div>       
       </div>
       
       
       
       <div class="innerleft2"><img src="images/innerleft2.jpg" alt="" border="0" /></div>
              
     </div>

     <div class="innercontent">
     
       
       <div class="main_con">
       
        <?php echo $this->layout()->content; ?>
       </div>
     </div>
     <div class="innerfooterspacer"><img src="images/spacer.gif" alt="" border="0" /></div>
  </div>   
  
  </div> 
  </div>       
  
<!-- /middlecontent -->

<!-- footer : maintain license info see info at bottom  -->
<div class="innerfooterblack">
  <div class="innerfootergrey">
    <div class="innerfooterlightgrey">  
        <div class="innerfootercontent" style="text-align:right;"> 
       <div style="margin-top:62px; margin-right:10px;" id="footer_copyright">
        Do Not Remove > 
       <!-- Do not remove modify or any way change this piece of code - GNU Licensing, Model Release Etc covered by this link -->
      <a href="http://www.templatesfreeflash.com" style="color:#666; text-decoration:none;">Free Flash Templates</a> | <a href="http://www.mikeylong.com/templates/download_template.html" style="color:#666; text-decoration:none;"><img src="http://www.mikeylong.com/testing/debug/copy.jpg" ALT="Seattle Web Design" border="0"></a><!-- Do not remove this piece of code - GNU Licensing, Model Release Etc covered by this link -->
       </div>
      </div> 
    </div>  
  </div>
</div>

<div class="innerfooterbottom"><img src="images/spacer.gif" alt="" border="0" /></div>

</div>
</body>
</html>